# Generated by Django 4.1.7 on 2023-08-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=277, verbose_name='Customer Email')),
            ],
        ),
    ]
